name: Mirror and run GitLab CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SimeonEhrig/gitlab-mirror-and-ci-action@addForkSupport
      with:
        args: "https://gitlab.com/hzdr/qedjl-project/test-trigger-gitlab.git"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "svboxel"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "47230590"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} /
